export const COLLECTION_DETAIL_HEADER_HEIGHT = 40;
export const COLLECTION_DETAIL_COLUMN_HEIGHT = 56;
export const COLLECTION_DETAIL_AMOUNT_FEE_COLUMN_MIN_WIDTH = '248px';
export const COLLECTION_DETAIL_ADDRESS_HASH_COLUMN_MIN_WIDTH = '320px';
export const COLLECTION_DETAIL_STATUS_COLUMN_MIN_WIDTH = '120px';
export const COLLECTION_DETAIL_TIME_COLUMN_MIN_WIDTH = '176px';

const COLLECTION_DETAIL_ROW_HEIGHT = 56;
const COLLECTION_DETAIL_HEADER_BLOCK = 40;

export function computeCollectionDetailDataListHeight(rowCount: number): number {
  return COLLECTION_DETAIL_HEADER_BLOCK + rowCount * COLLECTION_DETAIL_ROW_HEIGHT;
}
