export const BULK_TRANSFER_DETAIL_HEADER_HEIGHT = 32;
export const BULK_TRANSFER_DETAIL_COLUMN_HEIGHT = 66;
export const BULK_TRANSFER_DETAIL_ROW_GAP_PX = 1;

export function computeBulkTransferDataListHeight(rowCount: number): number {
  if (rowCount <= 0) {
    return BULK_TRANSFER_DETAIL_HEADER_HEIGHT;
  }

  return (
    BULK_TRANSFER_DETAIL_HEADER_HEIGHT
    + rowCount * (BULK_TRANSFER_DETAIL_COLUMN_HEIGHT + BULK_TRANSFER_DETAIL_ROW_GAP_PX)
    + BULK_TRANSFER_DETAIL_ROW_GAP_PX
  );
}

export const BULK_TRANSFER_DETAIL_AMOUNT_ID_COLUMN_MIN_WIDTH = '248px';
export const BULK_TRANSFER_DETAIL_HASH_SENDER_COLUMN_MIN_WIDTH = '248px';
export const BULK_TRANSFER_DETAIL_STATUS_COLUMN_MIN_WIDTH = '145px';
export const BULK_TRANSFER_DETAIL_ONCHAIN_TIME_COLUMN_MIN_WIDTH = '200px';
